################################################################################
# If modified, these settings will be copied into your config overrides
# folder under `Modules.zombiemode`:
#
# Modules:
#   zombiemode:
#     Enabled: true
################################################################################
# - Enabled -
#   Set to false to disable zombie mode server-wide.
Enabled: true
# - MaximumRoam -
#   Maximum roam radius a player may set. 0 means no limit.
MaximumRoam: 0
# - MaxWaypoints -
#   Maximum number of waypoints a player may define. 0 means no limit.
MaxWaypoints: 10
