---
name: "Setup Go"
description: "Setup Go using go.mod"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v6.4.0
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
